version: '3.9'

services:
  flask-app:
    container_name: flask-app
    image: flask-app-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - FLASK_ENV=production
    env_file:
      - .env
    restart: always
    # command: ["gunicorn", "--timeout", "0", "--workers", "4", "-b", "0.0.0.0:8000", "app:app"]

  redis:
    container_name: redis-container
    image: "redis:8.0-M03-alpine"
    restart: always
    env_file:
      - .env
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis-data:/data
  
  nginx:
    container_name: nginx-container
    image: nginx:1.27.4
    restart: always
    depends_on:
      - flask-app
    ports:
      - "80:80"   # Expose Nginx
      - "443:443" # For HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro  # Mount Nginx config
      - ./static:/app/static

volumes:
  redis-data: